### ISSUE TITLE
FEATURE: Enhance enemies

### ISSUE THREAD

**Issue by OcelotWalrus** [lumbar527/Dungeons-of-Kathallion#15]
I'm here to make a proposal:

What if we made a `mobs.yaml` file, like the `items.yaml` where we will store all mobs in a syntax like this:
```
<mob name>:
  damage:
    min_damage: <int>
    max_damage: <int>
  swiftness: <int> # only if we decide to add the swiftness attribute, from https://github.com/lumbar527/Dungeons-of-Kathallion/pull/14#issuecomment-1679469479
  health:
    min_spawning_health: <int> # the minimum amount of health that the enemy can have when spawning
    max_spawning_health: <int> # the maximum    "    "    "    "    "    "    "    "    "      "
    max_health_level: <int> # the health limit
  inventory:
    - <items> # which items you have a chance to drop when killing this enemy. I also think we should make so that you can have more than 1 items per each item (like having 2 axes), but not the 'Utility' typed items. And maybe add a limit to the player inventory (for example 7 items by default, but the player will be able to get 'bag' items to get more inventory slots). We'll also need to make that items on the ground that the player find cannot be found back.
      ...
  description: <string> # add a small description of the enemy, maybe it won't be shown when fighting, but it could be shown on a new command where it shows all mobs you've killed. Like on a stat command, where it prints your xp, the mobs you've encountered on your journey and how many you've killed.
```

So for example:
```
Goblin:
  damage:
    min_damage: 1
    max_damage: 4
  swiftness: 1.3
  health:
    min_spawning_health: 4
    max_spawning_health: 8
    max_health_level: 9
  inventory:
    - Wooden Stick
    - Healing Potion
  description: "The Goblin may be an easy enemy to beat, but in groups, they can be very annoying to deal with."
```
